<a href="https://colab.research.google.com/github/myungsworld/Machine-learning/blob/master/Hidden_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

보스턴 집값 예측

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [4]:
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [6]:
독립 = 보스턴[['crim', 'zn', 'indus', 'chas',
            'nox', 'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape,종속.shape)

(506, 13) (506, 1)


In [11]:
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [8]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')

In [20]:
model.fit(독립,종속, epochs=100, verbose=0)
model.fit(독립,종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 13.4400
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 13.5695
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 13.6063
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2948
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 13.7703
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 14.2131
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 13.5169
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 13.1414
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 13.8347
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 13.0784


In [21]:
print(model.predict(독립[:5]))
print(종속[:5])

[[32.624832]
 [22.087421]
 [33.246708]
 [34.068127]
 [31.286509]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


아이리스 품종 분류

In [24]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

#원핫인코딩
아이리스 = pd.get_dummies(아이리스)
아이리스.columns


Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [25]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [32]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss ='categorical_crossentropy', metrics='accuracy')

In [ ]:
model.fit(독립,종속, epochs=100)

In [40]:
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9935037e-01 6.4967998e-04 7.3347977e-09]
 [9.9876970e-01 1.2302480e-03 1.5237203e-08]
 [9.9880588e-01 1.1941611e-03 3.1131119e-08]
 [9.9845457e-01 1.5454112e-03 3.9634969e-08]
 [9.9931753e-01 6.8245508e-04 1.1311724e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [41]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[3.0894441e-08 6.7240588e-02 9.3275934e-01]
 [6.2543577e-08 7.2872698e-02 9.2712718e-01]
 [2.5968262e-07 1.8682927e-01 8.1317049e-01]
 [4.0025338e-08 4.7365118e-02 9.5263481e-01]
 [8.4210541e-07 2.1481511e-01 7.8518403e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
